#!/bin/sh

s3cmd ls --recursive s3://clk-splicing/SRP091981/ |  grep '.bam' | ruby -rdate -ne 'date, time, size, uri = $_.split; puts uri if size == "0"' | xargs s3cmd del
ls -s clk-splicing/SRP091981/ | grep .bam | ruby -ne 'size, name = $_.split; puts name if size == "0"' | xargs -I {} rm 'clk-splicing/SRP091981/{}'

s3cmd ls --recursive s3://clk-splicing/SRP091981-turbo/ |  grep '.bam' | ruby -rdate -ne 'date, time, size, uri = $_.split; puts uri if size == "0"' | xargs s3cmd del
ls -s clk-splicing/SRP091981-turbo/ | grep .bam | ruby -ne 'size, name = $_.split; puts name if size == "0"' | xargs -I {} rm 'clk-splicing/SRP091981-turbo/{}'