restart-times: 0
cluster: "slurm_scheduler.py" #
cluster-status: "slurm_status.py" #
cluster-config: "slurm_cluster_spec.yaml" #abs path
max-jobs-per-second: 1
max-status-checks-per-second: 10
#cores: 99 # how many jobs you want to submit to your cluster queue
local-cores: 1
rerun-incomplete: true
conda-prefix: "" # path to folder where to save conda envs
keep-going: true
